PADV-414: LTI launch course permission
Pearson-Advance/openedx-lti-tool-plugin pull request #10
Opened 2023-07-31 19:31 UTC by kuipumu

## Ticket

https://agile-jira.pearson.com/browse/PADV-414

## Description

This PR adds a course permission to the LTI launch view. We included this feature to restrict access to courses per LTI tool, this feature can be enabled with the 'openedx_lti_tool_plugin.course_access_configuration' waffle switch. In order to make the course permission to work this includes a CourseAccessConfiguration model, this model stores a list of courses ID allowed for a LTI tool, on the LTI launch view, if the feature is enabled, it will verify the requested course ID exists for the tool configuration, if not, it will return a HTTP 400 error.

## Type of Change

- [x] Add CourseAccessConfiguration middleware class.
- [x] Add COURSE_ACCESS_CONFIGURATION WaffleSwitch.
- [x] Modify LtiToolLaunchView post method.
- [x] Add edx-toggles base.in requirement.
- [x] Upgrade requirements.
- [x] Include tests for all added  and modified code.

## Testing:

- Run the LMS: `make dev.up.lms`.
- Install `openedx_lti_tool_plugin` on the LMS.
- Add required settings to LMS.
	
```
# Enable LTI Tool Provider Plugin.
OLTITP_ENABLE_LTI_TOOL = True
```

- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a new LTI 1.3 tool config: http://localhost:18000/admin/lti1p3_tool_config/ltitool/add/

```
Issuer: https://saltire.lti.app/platform
Client id: saltire.lti.app
Auth login: url: https://saltire.lti.app/platform/auth
Auth token url: https://saltire.lti.app/platform/token/sda42bb0cf2352259a367a404d48d54e8
Key set url: https://saltire.lti.app/platform/jwks/sda42bb0cf2352259a367a404d48d54e8
Deployment ids: ["cLWwj9cbmkSrCNsckEFBmA"]
```

- Create a new CourseAccessConfiguration instance for the previously created LTI tool and include the course_id in the "Allowed Course IDs" list.
- Go to the saLTIre platform https://saltire.lti.app/platform
- Go to "Security Model" on the left sidebar and set these settings:

```
Message URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/launch/{course_id}
Initiate login URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/login
Redirection URI(s): https://{ngrok_url}/openedx_lti_tool_plugin/1.3/launch/{course_id}
Public keyset URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/pub/jwks
```

- Click on the "Save" button on the top navbar.
- Click on the dropdown next to the "Connect" button on the top navbar.
- Click on "Open in iframe".
- The launch should work.
- Repeat the launch with a different Message URL (Also update Redirection URI(s) field to include the new message URL).
- The launch should fail with a HTTP 400 response.

## Reviewers

- [ ] @Squirrel18 
- [ ] @alexjmpb

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_models.py
> +        self.allowed_course_ids = ['id-1', 'id-2']
Shouldn't allowed_course_ids be a JSON string?

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_models.py
> +        self.assertEqual(self.profile.is_course_id_allowed('id-1'), True)
```suggestion
        self.assertTrue(self.profile.is_course_id_allowed('id-1'))
```

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_models.py
> +        self.assertEqual(self.profile.is_course_id_allowed('id-3'), False)
```suggestion
        self.assertFalse(self.profile.is_course_id_allowed('id-3'))
```

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/waffle.py
> +)
```suggestion

WAFFLE_NAMESPACE = AppConfig.name

COURSE_ACCESS_CONFIGURATION = WaffleSwitch(
    f'{WAFFLE_NAMESPACE}.course_access_configuration', __name__
)
```

What do you think of adding this constant to be more explicit?

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_views.py
> +        course_access_configuration_mock.is_enabled.return_value = True
What do you think of using this decorator https://github.com/openedx/edx-toggles/blob/master/edx_toggles/toggles/testutils.py#L7 to mock the value of the waffle flag?

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_views.py
> +        course_access_configuration_filter_mock().first().is_course_id_allowed.assert_called_once_with(COURSE_ID)
```suggestion
        course_access_configuration_filter_mock().first.assert_called_once_with()
course_access_configuration_filter_mock().first().is_course_id_allowed.assert_called_once_with(COURSE_ID)
```

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_views.py
> +        course_access_configuration_mock.is_enabled.return_value = False
Same comment about using https://github.com/openedx/edx-toggles/blob/master/edx_toggles/toggles/testutils.py#L7

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_views.py
> +        course_access_configuration_mock.is_enabled.return_value = True
Same comment about using https://github.com/openedx/edx-toggles/blob/master/edx_toggles/toggles/testutils.py#L7

2023-08-03 14:37 UTC, alexjmpb commented on openedx_lti_tool_plugin/tests/test_views.py
> +        course_access_configuration_mock.is_enabled.return_value = True
Same comment about using https://github.com/openedx/edx-toggles/blob/master/edx_toggles/toggles/testutils.py#L7

2023-08-14 20:52 UTC, Jacatove commented on openedx_lti_tool_plugin/models.py
> +    )
Is this field going to be used only trough the admin panel?. If yes, what do you think about including a course id validator?.
Didn't you consider making a many to many relationship to courses? I suppose this is not going to be friendly in admin panel.

@kuipumu

2023-08-15 20:24 UTC, Squirrel18 requested changes

2023-08-15 20:24 UTC, Squirrel18 commented on openedx_lti_tool_plugin/signals.py
> +@receiver(post_save, sender=LtiTool, dispatch_uid='create_access_configuration_on_lti_tool_create')
```suggestion
@receiver(post_save, sender=LtiTool, dispatch_uid='create_access_configuration_on_lti_tool_creation')
```

2023-08-15 20:24 UTC, Squirrel18 commented on openedx_lti_tool_plugin/tests/test_views.py
> +    def test_post_with_course_launch(
Please, check that CourseAccessConfiguration.objects.filter and self.tool_config.get_lti_tool have been called with the correct parameters. @kuipumu

2023-08-17 01:10 UTC, Squirrel18 approved these changes

2023-08-17 01:40 UTC, merged