PADV 658 - Filter unavailable units on course outline
Pearson-Advance/openedx-lti-tool-plugin pull request #18
Opened 2023-08-31 03:32 UTC by alexjmpb

## Ticket

https://agile-jira.pearson.com/browse/PADV-658

## Description

This PR applies a fix to filter out the units that are not yet published. After some discussion on how we are obtaining the outline data, we came to the conclusion of applying this fix to cover this case and make a further work on re-implementing the course outline and navigation functionalities for a LTI launch in such a way that the performance impact is reduced to minimum.

## Type of Change

- [x] Filter out unpublished units from outline

## Testing:

- Run the LMS: `make dev.up.lms`.
- Install `openedx_lti_tool_plugin` on the LMS.
- Add required settings to LMS.
	
```
# Enable LTI Tool Provider Plugin.
OLTITP_ENABLE_LTI_TOOL = True
```

- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a new LTI 1.3 tool config: http://localhost:18000/admin/lti1p3_tool_config/ltitool/add/

```
Issuer: https://saltire.lti.app/platform
Client id: saltire.lti.app
Auth login: url: https://saltire.lti.app/platform/auth
Auth token url: https://saltire.lti.app/platform/token/sda42bb0cf2352259a367a404d48d54e8
Key set url: https://saltire.lti.app/platform/jwks/sda42bb0cf2352259a367a404d48d54e8
Deployment ids: ["cLWwj9cbmkSrCNsckEFBmA"]
```

- Go to the saLTIre platform https://saltire.lti.app/platform
- Go to "Security Model" on the left sidebar and set these settings:

```
Message URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/launch/{course_id}
Initiate login URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/login
Redirection URI(s): https://{ngrok_url}/openedx_lti_tool_plugin/1.3/launch/{course_id}
Public keyset URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/pub/jwks
```

- Click on the "Save" button on the top navbar.
- On the course you made, create a new unit and do not publish it.
- Click on the dropdown next to the "Connect" button on the top navbar.
- Click on "Open in iframe".
- The launch should fail and show a message in the logs.
- Try again but now enabling the waffle switch `openedx_lti_tool_plugin.allow_complete_course_launch`
- The unpublished unit should not show in the outline.

## Reviewers

- [ ] @Squirrel18 
- [ ] @kuipumu

2023-08-31 17:51 UTC, Squirrel18 requested changes

2023-08-31 17:51 UTC, Squirrel18 commented on openedx_lti_tool_plugin/utils.py
> +            qualifiers={'block_type': 'vertical'}
Trailing comma. @alexjmpb

2023-08-31 17:51 UTC, Squirrel18 commented on openedx_lti_tool_plugin/utils.py
> +            sequence_id = sequence.get('id')
This variable is only used once. @alexjmpb

2023-08-31 17:51 UTC, Squirrel18 commented on openedx_lti_tool_plugin/utils.py
> +            if sequence_id not in available_sequences:
Remove the sequence that is not available from chapter. @alexjmpb

2023-08-31 21:45 UTC, kuipumu commented on openedx_lti_tool_plugin/tests/test_utils.py
> +        self.assertEqual(outline, COURSE_BLOCKS)
```suggestion

        self.assertEqual(get_course_outline(self.request_mock, COURSE_ID), COURSE_BLOCKS)
```
@alexjmpb What do you think about assert the call without defining the variable?

2023-08-31 21:45 UTC, kuipumu commented on openedx_lti_tool_plugin/tests/test_utils.py
> +        )
```suggestion

        self.assertEqual(
            get_course_outline(self.request_mock, COURSE_ID),
            {'children': [{'children': [{'id': 'test-sequence', 'children': []}]}]},
        )
```
@alexjmpb Same has previous comment

2023-08-31 21:46 UTC, kuipumu commented on openedx_lti_tool_plugin/tests/test_utils.py
> +            outline,
```suggestion
            get_course_outline(self.request_mock, COURSE_ID),
```
Same has previous comment

2023-08-31 21:47 UTC, kuipumu commented on openedx_lti_tool_plugin/edxapp_wrapper/backends/modulestore_module_o_v1.py
> +    """Return modulestore class."""
```suggestion
    """Return modulestore function."""
```

2023-08-31 21:47 UTC, kuipumu commented on openedx_lti_tool_plugin/edxapp_wrapper/modulestore_module.py
> +    """Return modulestore class."""
```suggestion
    """Return modulestore function."""
```

2023-09-01 04:25 UTC, kuipumu approved these changes

2023-09-01 20:02 UTC, Squirrel18 approved these changes

2023-09-01 21:03 UTC, merged