PADV-353: Add LTI view permission middleware
Pearson-Advance/openedx-lti-tool-plugin pull request #9
Opened 2023-07-25 22:00 UTC by kuipumu

## Ticket

https://agile-jira.pearson.com/browse/PADV-353

## Description

This PR adds a LTI view permission middleware, this middleware is in charge of controlling access for LTI users (users with a LTI profile) to views on the platform, this will logout any LTI user trying to access a view other than the views on the LTI plugin, views required by XBlocks on edx-platform and/or third-party packages installed on edx-platform. Third-party packages XBlocks with views that should restricted by LTI users can add new blocklisted URL patterns to the OLTITP_URL_BLOCKLIST setting. Views on the edx-platform that should be whitelisted and are not on the default list can be added to the OLTITP_URL_WHITELIST setting.

## Type of Change

- [x] Add LtiViewPermissionMiddleware middleware class.
- [x] Add OLTITP_URL_BLOCKLIST setting.
- [x] Add OLTITP_URL_WHITELIST setting.
- [x] Add LtiViewPermissionMiddleware to MIDDLEWARE settings.
- [x] Include tests for all added code.

## Testing:

- Run the LMS: `make dev.up.lms`.
- Install `openedx_lti_tool_plugin` on the LMS.
- Add required settings to LMS.
	
```
# Enable LTI Tool Provider Plugin.
OLTITP_ENABLE_LTI_TOOL = True
```

- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a new LTI 1.3 tool config: http://localhost:18000/admin/lti1p3_tool_config/ltitool/add/

```
Issuer: https://saltire.lti.app/platform
Client id: saltire.lti.app
Auth login: url: https://saltire.lti.app/platform/auth
Auth token url: https://saltire.lti.app/platform/token/sda42bb0cf2352259a367a404d48d54e8
Key set url: https://saltire.lti.app/platform/jwks/sda42bb0cf2352259a367a404d48d54e8
Deployment ids: ["cLWwj9cbmkSrCNsckEFBmA"]
```

- Go to the saLTIre platform https://saltire.lti.app/platform
- Go to "Security Model" on the left sidebar and set these settings:

```
Message URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/launch/{course_id}
Initiate login URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/login
Redirection URI(s): https://{ngrok_url}/openedx_lti_tool_plugin/1.3/launch/{course_id}
Public keyset URL: https://{ngrok_url}/openedx_lti_tool_plugin/1.3/pub/jwks
```

- Click on the "Save" button on the top navbar.
- Click on the dropdown next to the "Connect" button on the top navbar.
- Click on "Open in iframe".
- The launch should work and you should be able to use all XBlocks without issue.
- Go to any blacklisted URL on edx-platform: http://localhost:18000/contact
- The user should by logout.
- On the launch, any new request should return a 404 response.

## Reviewers

- [ ] @Squirrel18 
- [ ] @alexjmpb

2023-07-27 02:38 UTC, alexjmpb commented on openedx_lti_tool_plugin/middleware.py
> +        url_whitelist = [
What do you think of defining these default urls patterns in a constant? a then join the constant list and the settings list here

2023-08-01 14:45 UTC, alexjmpb approved these changes

2023-08-02 21:09 UTC, Squirrel18 requested changes

2023-08-02 21:09 UTC, Squirrel18 commented on openedx_lti_tool_plugin/tests/test_middleware.py
> +    def test_process_view_without_lti_profile(self, filter_mock: MagicMock):
Check that logout function has been called. @kuipumu

2023-08-02 21:21 UTC, Squirrel18 approved these changes

2023-08-03 14:48 UTC, merged